version: "3.9"
services:
  biketeam:
    image: github.com/tomacla/biketeam:latest
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    volumes:
      - /opt/biketeam:/opt/biketeam
    networks:
      biketeam:
        aliases:
          - biketeam.localhost
